### ISSUE TITLE
error widget couldn't show

### ISSUE THREAD

**Issue by tegarnugroho** [realdiganta/video-thumbnail-generator#1]
in this image, i try to make error with stop internet connection and i already set error widget but nothings changed. still show the message error
"The getter 'length' was called on null.
Receiver: null
Tried calling: length"

![image](https://user-images.githubusercontent.com/35763779/107001767-c9acf500-67bc-11eb-8b53-16b8c5c88fda.png)
![image](https://user-images.githubusercontent.com/35763779/107001958-214b6080-67bd-11eb-80a0-67728c92a06e.png)

**Comment by jscottanderson** [comment]
@skripsimu I am also experiencing the same issue! cc: @realdiganta

**Comment by dxganta** [comment]
Thank you for raising an issue on this bug. It has been fixed.
